### ISSUE TITLE
why you exclude me? i'm kind :(((

### ISSUE THREAD

**Issue by OniriCorpe** [june-coloc/EnergyDrink-license#1]
i'm liberal so left-wing and i can't use stuff with this licence
that's fascist 😉😉😉

**Comment by juin-en-anglais** [comment]
OK socdem.

**Comment by OniriCorpe** [comment]
why are you being so rude?

**Comment by juin-en-anglais** [comment]
Please, see my last commit: https://github.com/june-coloc/EnergyDrink-license/commit/36877f9271241196f4fd018d3a998515f01cf287
